export const PLATFORM_BILLING_FRONTEND_SHELL =
  import.meta.env.VITE_PLATFORM_BILLING_FRONTEND_SHELL === "true";
export const PLATFORM_BILLING_ENABLE_INTERACTIVE =
  import.meta.env.VITE_PLATFORM_BILLING_ENABLE_INTERACTIVE === "true";
